# Generated by Django 4.2.10 on 2024-02-16 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprofile',
            name='adventure_level',
            field=models.CharField(choices=[('E', 'Extreme'), ('A', 'High'), ('M', 'Medium'), ('B', 'Low'), ('N', 'None')], default='N', verbose_name='Adventure Level'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='animals',
            field=models.BooleanField(default=False, verbose_name='Animals'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='food_restrictions',
            field=models.CharField(max_length=200, verbose_name='Food Restrictions'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='n_adults',
            field=models.IntegerField(default=0, verbose_name='Number of Adults'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='n_babies',
            field=models.IntegerField(default=0, verbose_name='Number of Babies'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='n_children',
            field=models.IntegerField(default=0, verbose_name='Number of Children'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='n_elderly',
            field=models.IntegerField(default=0, verbose_name='Number of Elderly'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='n_teenagers',
            field=models.IntegerField(default=0, verbose_name='Number of Teenagers'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='observations',
            field=models.TextField(max_length=400, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_currency',
            field=models.CharField(verbose_name='Preferred Currency'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_languages',
            field=models.CharField(verbose_name='Preferred Languages'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='reason',
            field=models.CharField(verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='reduced_mobility',
            field=models.BooleanField(default=False, verbose_name='Reduced Mobility'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_cities',
            field=models.ManyToManyField(to='services.city', verbose_name='Favorite Cities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_countries',
            field=models.ManyToManyField(to='services.country', verbose_name='Favorite Countries'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_poas',
            field=models.ManyToManyField(to='services.poa', verbose_name='Favorite Points of Accommodation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_poes',
            field=models.ManyToManyField(to='services.poe', verbose_name='Favorite Points of Entertainment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_pois',
            field=models.ManyToManyField(to='services.poi', verbose_name='Favorite Points of Interest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Phone Number'),
        ),
    ]
