# Generated by Django 4.2.10 on 2024-03-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_poa_type_alter_poe_type_alter_poi_type'),
        ('users', '0002_alter_travelprofile_adventure_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_pogs',
            field=models.ManyToManyField(to='services.pog', verbose_name='Favorite Gastronomy Points'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_poas',
            field=models.ManyToManyField(to='services.poa', verbose_name='Favorite Accommodation Points'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_poes',
            field=models.ManyToManyField(to='services.poe', verbose_name='Favorite Entertainment Points'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_pois',
            field=models.ManyToManyField(to='services.poi', verbose_name='Favorite Interest Points'),
        ),
    ]
