# Generated by Django 4.2.10 on 2024-04-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_fav_pogs_alter_user_fav_poas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelprofile',
            name='pref_poe',
            field=models.CharField(default=1, verbose_name='Point of Entertainment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelprofile',
            name='pref_pog',
            field=models.CharField(default=1, verbose_name='Point of Gastronomy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelprofile',
            name='pref_poi',
            field=models.CharField(default=1, verbose_name='Point of Interest'),
            preserve_default=False,
        ),
    ]
