# Generated by Django 4.2.10 on 2024-04-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_travelprofile_pref_poe_travelprofile_pref_pog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelprofile',
            name='pref_poa',
            field=models.CharField(default='', verbose_name='Point of Accommodation'),
            preserve_default=False,
        ),
    ]
