# Generated by Django 4.2.10 on 2024-04-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_travelprofile_pref_poa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_poa',
            field=models.CharField(default='[]', verbose_name='Point of Accommodation'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_poe',
            field=models.CharField(default='[]', verbose_name='Point of Entertainment'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_pog',
            field=models.CharField(default='[]', verbose_name='Point of Gastronomy'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_poi',
            field=models.CharField(default='[]', verbose_name='Point of Interest'),
        ),
    ]
