# Generated by Django 4.2.10 on 2024-04-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_travelprofile_pref_poa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='food_restrictions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Food Restrictions'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='observations',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_currency',
            field=models.CharField(blank=True, null=True, verbose_name='Preferred Currency'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='pref_languages',
            field=models.CharField(blank=True, null=True, verbose_name='Preferred Languages'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='reason',
            field=models.CharField(default='[]', verbose_name='Reason'),
        ),
    ]
