# Generated by Django 4.2.10 on 2024-04-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_travelprofile_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelprofile',
            name='pref_currency',
        ),
        migrations.RemoveField(
            model_name='travelprofile',
            name='pref_languages',
        ),
    ]
