# Generated by Django 4.2.10 on 2024-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_travelprofile_pref_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprofile',
            name='food_restrictions',
            field=models.CharField(default='', max_length=200, verbose_name='Food Restrictions'),
        ),
        migrations.AlterField(
            model_name='travelprofile',
            name='observations',
            field=models.TextField(default='', max_length=400, verbose_name='Observations'),
        ),
    ]
