# Generated by Django 4.2.10 on 2024-04-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_travelprofile_food_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprofile',
            name='adventure_level',
            field=models.CharField(choices=[('E', 'Extreme'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low'), ('N', 'None')], default='N', verbose_name='Adventure Level'),
        ),
    ]
