# Generated by Django 4.2.10 on 2024-02-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(verbose_name='Information Language')),
                ('name', models.CharField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('presentation', models.TextField(verbose_name='Presentation')),
                ('languages', models.TextField(verbose_name='Languages')),
                ('history', models.TextField(verbose_name='History')),
                ('curiosities', models.TextField(verbose_name='Curiosities')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='City Base')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.TextField(verbose_name='Point Identifier Name')),
                ('lang', models.CharField(verbose_name='Information Language')),
                ('name', models.TextField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('presentation', models.TextField(verbose_name='Presentation')),
                ('location', models.TextField(verbose_name='Location')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('price_avg', models.TextField(verbose_name='Price Average')),
                ('shedule_avg', models.TextField(verbose_name='Shedule Average')),
                ('history', models.TextField(verbose_name='History')),
                ('type', models.TextField(choices=[('O', 'Other'), ('M', 'Museum'), ('E', 'Emblematic Site'), ('P', 'Park/Garden'), ('T', 'Theater'), ('C', 'Church'), ('L', 'Library'), ('S', 'Square')], default='O', verbose_name='Type')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Point of Information',
                'verbose_name_plural': 'Points of Information',
                'db_table': 'services_poi',
            },
        ),
        migrations.CreateModel(
            name='Poe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.TextField(verbose_name='Point Identifier Name')),
                ('lang', models.CharField(verbose_name='Information Language')),
                ('name', models.TextField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('presentation', models.TextField(verbose_name='Presentation')),
                ('location', models.TextField(verbose_name='Location')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('price_avg', models.TextField(verbose_name='Price Average')),
                ('shedule_avg', models.TextField(verbose_name='Shedule Average')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.TextField(choices=[('O', 'Other'), ('S', 'Shop'), ('C', 'Cinema'), ('B', 'Bowling alley'), ('N', 'Nightclub'), ('M', 'Mall'), ('T', 'Theme Park')], default='O', verbose_name='Type')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Point of Entertainment',
                'verbose_name_plural': 'Points of Entertainment',
                'db_table': 'services_poe',
            },
        ),
        migrations.CreateModel(
            name='Poa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.TextField(verbose_name='Point Identifier Name')),
                ('lang', models.CharField(verbose_name='Information Language')),
                ('name', models.TextField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('presentation', models.TextField(verbose_name='Presentation')),
                ('location', models.TextField(verbose_name='Location')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('price_avg', models.TextField(verbose_name='Price Average')),
                ('shedule_avg', models.TextField(verbose_name='Shedule Average')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.TextField(choices=[('O', 'Other'), ('HO', 'Hotel'), ('HE', 'Hostel'), ('CA', 'Camping'), ('CR', 'Rural House'), ('A', 'Shelter')], default='O', verbose_name='Type')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Point of Accommodation',
                'verbose_name_plural': 'Points of Accommodation',
                'db_table': 'services_poa',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(verbose_name='Information Language')),
                ('name', models.CharField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('presentation', models.TextField(verbose_name='Presentation')),
                ('national_day', models.TextField(verbose_name='National Day')),
                ('population', models.TextField(verbose_name='Total Population')),
                ('density', models.TextField(verbose_name='Population Density')),
                ('age_structure', models.TextField(verbose_name='Age Structure')),
                ('languages', models.TextField(verbose_name='Languages')),
                ('currency', models.TextField(verbose_name='Currency')),
                ('police', models.TextField(verbose_name='Police')),
                ('firefighter', models.TextField(verbose_name='Firefighter')),
                ('ambulance', models.TextField(verbose_name='Ambulance')),
                ('history', models.TextField(verbose_name='History')),
                ('curiosities', models.TextField(verbose_name='Curiosities')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Country Base')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'unique_together': {('country', 'lang')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.country', verbose_name='Country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city', 'lang')},
        ),
    ]
