# Generated by Django 4.2.10 on 2024-03-10 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.TextField(verbose_name='Point Identifier Name')),
                ('lang', models.CharField(verbose_name='Information Language')),
                ('name', models.TextField(verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('presentation', models.TextField(verbose_name='Presentation')),
                ('location', models.TextField(verbose_name='Location')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('price_avg', models.TextField(verbose_name='Price Average')),
                ('shedule_avg', models.TextField(verbose_name='Shedule Average')),
                ('description', models.TextField(verbose_name='Description')),
                ('type', models.TextField(choices=[('O', 'Other'), ('R', 'Restaurant'), ('B', 'Bar'), ('C', 'Cafeteria'), ('F', 'Fast Food'), ('T', 'Tabern')], default='O', verbose_name='Type')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Point of Gastronomy',
                'verbose_name_plural': 'Points of Gastronomy',
                'db_table': 'services_pog',
            },
        ),
    ]
