# Generated by Django 4.2.10 on 2024-03-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_pog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poa',
            name='type',
            field=models.TextField(choices=[('O', 'Other'), ('HO', 'Hotel'), ('HE', 'Hostel'), ('C', 'Camping'), ('R', 'Rural House'), ('S', 'Shelter')], default='O', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='poe',
            name='type',
            field=models.TextField(choices=[('O', 'Other'), ('C', 'Cinema'), ('B', 'Bowling alley'), ('N', 'Nightclub'), ('M', 'Mall/Shop'), ('T', 'Theme Park'), ('B', 'Beach')], default='O', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='type',
            field=models.TextField(choices=[('O', 'Other'), ('M', 'Museum'), ('E', 'Emblematic Site'), ('P', 'Park/Garden'), ('T', 'Theater'), ('C', 'Church'), ('S', 'Street/Square')], default='O', verbose_name='Type'),
        ),
    ]
