# Generated by Django 4.2.10 on 2024-04-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_poa_type_alter_poe_type_alter_poi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poe',
            name='type',
            field=models.TextField(choices=[('O', 'Other'), ('C', 'Cinema'), ('B', 'Bowling Alley'), ('N', 'Nightclub'), ('M', 'Mall/Shop'), ('T', 'Theme Park'), ('B', 'Beach')], default='O', verbose_name='Type'),
        ),
    ]
