# Generated by Django 4.2.10 on 2024-12-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_poe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poa',
            name='image_url',
            field=models.URLField(default=None, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='poe',
            name='image_url',
            field=models.URLField(default=None, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='pog',
            name='image_url',
            field=models.URLField(default=None, null=True, verbose_name='Image URL'),
        ),
        migrations.AddField(
            model_name='poi',
            name='image_url',
            field=models.URLField(default=None, null=True, verbose_name='Image URL'),
        ),
    ]
