# Generated by Django 4.2.10 on 2024-02-24 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('state', models.CharField(choices=[('P', 'Planned'), ('I', 'In Progress'), ('F', 'Finished'), ('C', 'Cancelled')], max_length=1, verbose_name='State')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='cities_light.city', verbose_name='Destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='cities_light.city', verbose_name='Origin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='RouteDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('presentation', models.TextField(verbose_name='Presentation')),
                ('presentation_es', models.TextField(verbose_name='Presentation ES')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Route Day',
                'verbose_name_plural': 'Route Days',
                'ordering': ['date'],
                'unique_together': {('route', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RouteDayActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(verbose_name='Activity')),
                ('moment', models.CharField(choices=[('M', 'Morning'), ('E', 'Evening'), ('N', 'Night')], verbose_name='Moment of the day')),
                ('type', models.CharField(choices=[('I', 'Interest'), ('E', 'Entertainment'), ('G', 'Gastronomy'), ('O', 'Other')], verbose_name='Activity Type')),
                ('lang', models.CharField(verbose_name='Information Language')),
                ('route_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.routeday', verbose_name='Route Day')),
            ],
            options={
                'verbose_name': 'Generic Activity',
                'verbose_name_plural': 'Generic Activities',
            },
        ),
        migrations.CreateModel(
            name='RouteDayActivityInterest',
            fields=[
                ('routedayactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.routedayactivity')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.poi', verbose_name='Point of Interest')),
            ],
            options={
                'verbose_name': 'Interest Activity',
                'verbose_name_plural': 'Interest Activities',
            },
            bases=('planner.routedayactivity',),
        ),
        migrations.CreateModel(
            name='RouteDayActivityEntertainment',
            fields=[
                ('routedayactivity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='planner.routedayactivity')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.poe', verbose_name='Point of Entertainment')),
            ],
            options={
                'verbose_name': 'Entertainment Activity',
                'verbose_name_plural': 'Entertainment Activities',
            },
            bases=('planner.routedayactivity',),
        ),
    ]
