# Generated by Django 4.2.10 on 2024-02-24 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='routedayactivity',
            table='planner_route_day_activity',
        ),
        migrations.AlterModelTable(
            name='routedayactivityentertainment',
            table='planner_route_day_activity_entertainment',
        ),
        migrations.AlterModelTable(
            name='routedayactivityinterest',
            table='planner_route_day_activity_interest',
        ),
    ]
