# Generated by Django 4.2.10 on 2024-02-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_routedayactivity_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routedayactivity',
            name='moment',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('N', 'Night')], verbose_name='Moment of the day'),
        ),
    ]
