# Generated by Django 4.2.10 on 2024-03-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_routedayactivity_moment'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Days'),
            preserve_default=False,
        ),
    ]
