# Generated by Django 4.2.10 on 2024-03-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_route_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='days',
            field=models.IntegerField(default=0, verbose_name='Days'),
        ),
    ]
