# Generated by Django 4.2.10 on 2024-03-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_route_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='slug',
        ),
    ]
