# Generated by Django 4.2.10 on 2024-04-14 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_travelprofile_pref_poa_and_more'),
        ('planner', '0008_route_poa_en_route_poa_es'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='travel_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.travelprofile', verbose_name='Travel Profile'),
        ),
    ]
