# Generated by Django 4.2.10 on 2024-05-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_route_travel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='explanation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation EN'),
        ),
        migrations.AddField(
            model_name='route',
            name='explanation_es',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation ES'),
        ),
    ]
